apps/funcionarios/urls.py
from django.urls import path

# from .views import home,
from .views import FuncionariosList, FuncionarioEdit, FuncionarioDelete, FuncionarioCreate

urlpatterns = [
    path('', FuncionariosList.as_view(), name='list_funcionarios'),
    path('novo/', FuncionarioCreate.as_view(), name='create_funcionario'),
    path('editar/<int:pk>', FuncionarioEdit.as_view(), name='update_funcionario'),
    path('delete/<int:pk>', FuncionarioDelete.as_view(), name='delete_funcionario'),
]

gestao_rh/urls.py
from django.contrib import admin
from django.conf  import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),


    path('', include('apps.core.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # ver os arquivos em desenvolvimento 

apps/documentos/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence  = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from apps.empresas.models import Empresa
from apps.departamentos.models import Departamento


class Funcionario(models.Model):
    nome = models.CharField(max_length=100, help_text="Nome do funcionário")
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True,
                                blank=True)

    def get_absolute_url(self):
        return reverse('list_funcionarios')

    def __str__(self):
        return self.nome

apps/funcionarios/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, UpdateView, DeleteView, CreateView

from .models import Funcionario


# @login_required
# def home(request):
#     return HttpResponse('Olá')


class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioCreate(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit=False) # Não enviar o objeto para o BD
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username="".join(funcionario.nome.split(" ")[:2]))
        funcionario.save()

        return super().form_valid(form)

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
    Edit
    <form method="post">
        {% csrf_token %}

        <h1>Você realmente deseja deletar {{ obj }}</h1>

        {{ form }}

        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
    Edit
    <form method="post">
        {% csrf_token %}

        {{ form|bootstrap }}

        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
    <br>

    {% if object %}
    <a href="{% url 'create_documento' object.id %}" class="btn btn-info">Adicionar Documento</a>
    {% endif %}

    <br>
    <br>

    {% for documento in object.documento_set.all %}
        <a href="{{ documento.arquivo.url }}">{{documento}}</a>
        <br>
    {% endfor %}
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}
    Lista
    <br>
    {% for funcionario in object_list %}
        <a href="{% url 'update_funcionario' funcionario.id %}">{{ funcionario }}</a>
        <a href="{% url 'delete_funcionario' funcionario.id %}">Deletar</a>
        <br>
    {% endfor %}

    <a href="{% url 'create_funcionario' %}" class="btn btn-info">Adicionar funcionário</a>
{% endblock %}